# Generated by Django 5.0.6 on 2024-06-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('proveedor', models.CharField(max_length=20)),
                ('rack', models.CharField(max_length=20)),
                ('sitio', models.CharField(max_length=20)),
                ('num_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('referente', models.CharField(max_length=30)),
                ('num_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('dirección', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('switchowner', models.CharField(max_length=30)),
                ('num_id', models.IntegerField()),
            ],
        ),
    ]
